import { defineConfig } from "oxlint";
import web from "oxlint-config-universe/web";

export default defineConfig({
  extends: [web],
  ignorePatterns: [
    ".agents/**",
    ".claude/**",
    ".cursor/**",
    "tools/oxlint/anti-slop/**",
    "src/test-setup.ts",
    "src/test-matchers.d.ts",
  ],
  jsPlugins: [{ name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" }],
  rules: {
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
    "anti-slop/require-tsdoc": "error",
    "jsdoc/no-blank-blocks": "error",
    "import/no-duplicates": "error",
    "import/first": "error",
    "import/newline-after-import": "error",
    "import/no-cycle": "error",
    "no-unused-vars": "error",
    "unicorn/no-empty-file": "error",
    "eslint/complexity": ["error", { max: 7, variant: "modified" }],
  },
  overrides: [
    {
      files: ["src/shared/lib/runtime-guards.ts"],
      rules: {
        "anti-slop/no-runtime-typeof": "off",
        "anti-slop/no-unknown-parameters": "off",
      },
    },
    {
      files: [
        "**/*.spec.{ts,tsx}",
        "**/*.test.{ts,tsx}",
        "**/__tests__/**/*.{ts,tsx}",
        "src/test-setup.ts",
        "src/test-matchers.d.ts",
        "**/test-setup.ts",
        "**/test-matchers.d.ts",
      ],
      rules: {
        "anti-slop/no-chained-type-assertions": "off",
        "anti-slop/no-conditional-empty-object-spread": "off",
        "anti-slop/no-known-value-widening": "off",
        "anti-slop/no-module-mocking": "off",
        "anti-slop/no-object-parameters": "off",
        "anti-slop/no-reflect-apply": "off",
        "anti-slop/no-reflect-get": "off",
        "anti-slop/no-runtime-typeof": "off",
        "anti-slop/no-shape-in-symbol-names": "off",
        "anti-slop/no-unknown-parameters": "off",
        "anti-slop/no-unknown-returns": "off",
        "anti-slop/no-unknown-type-aliases": "off",
        "anti-slop/no-unsafe-dictionary-type": "off",
        "anti-slop/no-widen-then-assert": "off",
        "anti-slop/require-safety-comment-for-type-assertion": "off",
        "anti-slop/require-tsdoc": "off",
        "eslint/complexity": "off",
      },
    },
    {
      files: [
        "**/*.spec-e2e.{js,jsx,ts,tsx}",
        "**/e2e/**/*.{js,jsx,ts,tsx}",
        "**/*.config.{js,jsx,ts,tsx,mjs,cjs}",
        "**/next.config.*",
        "**/vite.config.*",
        "**/vitest.config.*",
        "**/jest.config.*",
        "**/metro.config.*",
        "**/babel.config.*",
        "**/postcss.config.*",
        "**/app.config.*",
      ],
      rules: {
        "eslint/complexity": "off",
      },
    },
    {
      files: ["src/features/**/*.{ts,tsx}", "src/shared/**/*.{ts,tsx}", "src/core/**/*.{ts,tsx}"],
      excludeFiles: ["src/shared/types/**/*.d.ts"],
      rules: {
        "import/no-default-export": "error",
        "react/jsx-curly-brace-presence": ["warn", { props: "ignore", children: "never" }],
      },
    },
    {
      files: [
        "src/app/**/layout.tsx",
        "src/app/**/page.tsx",
        "src/app/**/error.tsx",
        "src/app/**/not-found.tsx",
        "src/app/**/loading.tsx",
        "src/app/**/template.tsx",
        "src/app/**/default.tsx",
        "src/app/**/global-error.tsx",
        "src/middleware.ts",
        "src/instrumentation.ts",
      ],
      rules: {
        "import/no-default-export": "off",
      },
    },
  ],
});
