// Export HTTP client
export { httpClient, getApiBaseUrl } from "./http";
export type { HttpClientConfig } from "./http";

// Export endpoint constants
export { endpoints } from "./endpoints";

// Export all shared types
export {
  AccessTargetEnum,
  type AccessTarget,
  AccessCapabilityEnum,
  type AccessCapability,
  AccessGrantRequestSchema,
  type AccessGrantRequest,
  UserAccessSnapshotSchema,
  type UserAccessSnapshot,
  ReplaceUserAccessRequestSchema,
  type ReplaceUserAccessRequest,
} from "./types/access.types";

export {
  type StatusValue,
  StatusValueSchema,
  type PaginationParams,
  PaginationParamsSchema,
  type ErrorResponseDto,
  ErrorResponseDtoSchema,
  type TopicSlug,
  TopicSlugSchema,
  type TopicViewDto,
  TopicViewDtoSchema,
  type TopicDetailDto,
  TopicDetailDtoSchema,
  type TopicLectureViewDto,
  TopicLectureViewDtoSchema,
  type AudioAssetViewDto,
  AudioAssetViewDtoSchema,
  type ListingViewDto,
  ListingViewDtoSchema,
  type ScholarRefDto,
  ScholarRefDtoSchema,
  type TopicRefDto,
  TopicRefDtoSchema,
  type AudioAssetDto,
  AudioAssetDtoSchema,
  type ListingRefDto,
  ListingRefDtoSchema,
  type SeriesContextDto,
  SeriesContextDtoSchema,
  type ListingDetailDto,
  ListingDetailDtoSchema,
  type ListingContentItemDto,
  ListingContentItemDtoSchema,
  type ListingModuleDto,
  ListingModuleDtoSchema,
  type ListingContentsDto,
  ListingContentsDtoSchema,
  type LastPlayedLessonDto,
  LastPlayedLessonDtoSchema,
  type ListingProgressSummaryDto,
  ListingProgressSummaryDtoSchema,
  type RelatedListingDto,
  RelatedListingDtoSchema,
  type AdminListingActionDto,
  AdminListingActionDtoSchema,
  type AdminListingListItemDto,
  AdminListingListItemDtoSchema,
  type AdminListingListDto,
  AdminListingListDtoSchema,
  type AdminListingDetailDto,
  AdminListingDetailDtoSchema,
  type BulkActionDto,
  BulkActionDtoSchema,
  type BulkActionResultDto,
  BulkActionResultDtoSchema,
  type CountryCode,
  CountryCodeSchema,
  COUNTRY_CODES,
  isCountryCode,
  validateCountryCode,
  COUNTRY_NAMES,
  COUNTRY_LIST,
  type ScholarViewDto,
  ScholarViewDtoSchema,
  type ScholarDetailDto,
  ScholarDetailDtoSchema,
  type ScholarDetailStats,
  ScholarDetailStatsSchema,
  type ScholarStatsDto,
  ScholarStatsDtoSchema,
  type ScholarListItemDto,
  ScholarListItemDtoSchema,
  type ScholarContentItemDto,
  ScholarContentItemDtoSchema,
  type ScholarContentUnifiedDto,
  ScholarContentUnifiedDtoSchema,
  type ScholarTopicsDto,
  ScholarTopicsDtoSchema,
  type AdminScholarListItemDto,
  AdminScholarListItemDtoSchema,
  type AdminScholarListDto,
  AdminScholarListDtoSchema,
  type ScholarListDto,
  ScholarListDtoSchema,
  type CollectionSummaryDto,
  CollectionSummaryDtoSchema,
  type SeriesSummaryDto,
  SeriesSummaryDtoSchema,
  type SingleSummaryDto,
  SingleSummaryDtoSchema,
  type ListingFormat,
  ListingFormatSchema,
  type ScholarTitle,
  ScholarTitleSchema,
  type PresignedUrlPurpose,
  PresignedUrlPurposeSchema,
  type PresignedUrlRequestDto,
  PresignedUrlRequestDtoSchema,
  type PresignedUrlResponseDto,
  PresignedUrlResponseDtoSchema,
  type BatchPresignAudioFile,
  BatchPresignAudioFileSchema,
  type BatchPresignAudioRequestDto,
  BatchPresignAudioRequestDtoSchema,
  type BatchPresignAudioResponseDto,
  BatchPresignAudioResponseDtoSchema,
  type SearchCatalogParams,
  SearchCatalogParamsSchema,
  type SearchCatalogItemDto,
  SearchCatalogItemDtoSchema,
  type SearchCatalogResultsDto,
  SearchCatalogResultsDtoSchema,
  type FeedContentItemDto,
  FeedContentItemDtoSchema,
  type FeedScholarRowDto,
  FeedScholarRowDtoSchema,
  type FeedTopicRowDto,
  FeedTopicRowDtoSchema,
  type FeedItemDto,
  FeedItemDtoSchema,
  type FeedPageDto,
  FeedPageDtoSchema,
  type LibraryItemDto,
  LibraryItemDtoSchema,
  type LibraryPageDto,
  LibraryPageDtoSchema,
  type SavedSyncItemDto,
  SavedSyncItemDtoSchema,
  type SavedSyncDto,
  SavedSyncDtoSchema,
  type SavedDeltaItemDto,
  SavedDeltaItemDtoSchema,
  type UserProfileDto,
  UserProfileDtoSchema,
  type StreamResponseDto,
  StreamResponseDtoSchema,
  type AudioProgressDto,
  AudioProgressDtoSchema,
  type ProgressSyncItemDto,
  ProgressSyncItemDtoSchema,
  type ProgressSyncDto,
  ProgressSyncDtoSchema,
  type AdminUserListItemDto,
  AdminUserListItemDtoSchema,
  type AdminUserListDto,
  AdminUserListDtoSchema,
  type ScholarChipDto,
  ScholarChipDtoSchema,
  type ContentSuggestionDto,
  ContentSuggestionDtoSchema,
  type RecentProgressDto,
  RecentProgressDtoSchema,
  type QuickBrowseDto,
  QuickBrowseDtoSchema,
  type TranslationStatus,
  TranslationStatusSchema,
  type TranslationViewDto,
  TranslationViewDtoSchema,
  type SaveTranslationDto,
  SaveTranslationDtoSchema,
  type TranslationTarget,
  TranslationTargetSchema,
  type Locale,
  LocaleSchema,
  SUPPORTED_LOCALES,
  DEFAULT_LOCALE,
  RTL_LOCALES,
  type ContentOriginalFields,
  ContentOriginalFieldsSchema,
  type ScholarOriginalFields,
  ScholarOriginalFieldsSchema,
  type ListingProgressDto,
  ListingProgressDtoSchema,
  type ProgressUpdateDto,
  ProgressUpdateDtoSchema,
  type CreateListingDto,
  CreateListingDtoSchema,
  type SaveListingTranslationDto,
  SaveListingTranslationDtoSchema,
  type UpdateListingTranslationDto,
  UpdateListingTranslationDtoSchema,
  type ListingFormDataDto,
  ListingFormDataDtoSchema,
  type UpdateListingDetailsDto,
  UpdateListingDetailsDtoSchema,
  type AdminListingMediaDetailDto,
  AdminListingMediaDetailDtoSchema,
  type UpdateListingMediaDto,
  UpdateListingMediaDtoSchema,
  type AdminArrangeLessonDto,
  AdminArrangeLessonDtoSchema,
  type AdminArrangeModuleDto,
  AdminArrangeModuleDtoSchema,
  type AdminArrangeDataDto,
  AdminArrangeDataDtoSchema,
  type ArrangeAudioRef,
  ArrangeAudioRefSchema,
  type ArrangeLessonOp,
  ArrangeLessonOpSchema,
  type ArrangeModuleOp,
  ArrangeModuleOpSchema,
  type ArrangeCommitDto,
  ArrangeCommitDtoSchema,
  type ArrangeCommitResultDto,
  ArrangeCommitResultDtoSchema,
  type SaveTopicTranslationDto,
  SaveTopicTranslationDtoSchema,
  type UpdateTopicTranslationDto,
  UpdateTopicTranslationDtoSchema,
  type AdminTopicDetailDto,
  AdminTopicDetailDtoSchema,
  type CreateTopicWithTranslationsDto,
  CreateTopicWithTranslationsDtoSchema,
  type UpdateTopicWithTranslationsDto,
  UpdateTopicWithTranslationsDtoSchema,
  type CreateScholarDto,
  CreateScholarDtoSchema,
  type UpdateScholarDto,
  UpdateScholarDtoSchema,
  type SaveScholarTranslationDto,
  SaveScholarTranslationDtoSchema,
  type UpdateScholarTranslationDto,
  UpdateScholarTranslationDtoSchema,
  type ScholarFormDataDto,
  ScholarFormDataDtoSchema,
  type UpdateProfileDto,
  UpdateProfileDtoSchema,
  type UpdateLocaleDto,
  UpdateLocaleDtoSchema,
  type SearchQueryDto,
  SearchQueryDtoSchema,
  type AppActions,
  type AppSubjectType,
  type ScholarSubject,
  type ListingSubject,
  type TranslationSubject,
  type MediaSubject,
  type AppSubjects,
  type AppAbility,
} from "./types";

// Export route constants
export { routes, routeDefinitions, resolveRouteAccess } from "./routes";
export type { RouteAccess, RouteDefinition } from "./routes";

// Export shared navigation metadata
export {
  SECTION_TABS,
  DEFAULT_TABS,
  SECTION_LABELS,
  SECTION_ROUTES,
  type Section,
  type TabConfig,
} from "./navigation";

// Export query utilities (client, keys, hooks)
export { createQueryClient, queryKeys } from "./query";
export { useApiQuery, initApiClient } from "./query/hooks";
