// Export HTTP client
export { httpClient, getApiBaseUrl } from "./http";
export type { HttpClientConfig } from "./http";

// Export endpoint constants
export { endpoints } from "./endpoints";

// Export all shared types
export {
  type StatusValue,
  StatusValueSchema,
  type PaginationParams,
  PaginationParamsSchema,
  type ErrorResponseDto,
  ErrorResponseDtoSchema,
  type TopicSlug,
  TopicSlugSchema,
  type TopicViewDto,
  TopicViewDtoSchema,
  type TopicDetailDto,
  TopicDetailDtoSchema,
  type TopicLectureViewDto,
  TopicLectureViewDtoSchema,
  type AudioAssetViewDto,
  AudioAssetViewDtoSchema,
  type ListingViewDto,
  ListingViewDtoSchema,
  type ScholarRefDto,
  ScholarRefDtoSchema,
  type TopicRefDto,
  TopicRefDtoSchema,
  type AudioAssetDto,
  AudioAssetDtoSchema,
  type ListingRefDto,
  ListingRefDtoSchema,
  type SeriesContextDto,
  SeriesContextDtoSchema,
  type ListingDetailDto,
  ListingDetailDtoSchema,
  type ListingContentItemDto,
  ListingContentItemDtoSchema,
  type ListingModuleDto,
  ListingModuleDtoSchema,
  type ListingContentsDto,
  ListingContentsDtoSchema,
  type LastPlayedLessonDto,
  LastPlayedLessonDtoSchema,
  type RelatedListingDto,
  RelatedListingDtoSchema,
  type AdminListingUpdateDto,
  AdminListingUpdateDtoSchema,
  type AdminListingActionDto,
  AdminListingActionDtoSchema,
  type AdminListingListItemDto,
  AdminListingListItemDtoSchema,
  type AdminListingListDto,
  AdminListingListDtoSchema,
  type AdminListingDetailDto,
  AdminListingDetailDtoSchema,
  type BulkActionDto,
  BulkActionDtoSchema,
  type BulkActionResultDto,
  BulkActionResultDtoSchema,
  type CountryCode,
  CountryCodeSchema,
  COUNTRY_CODES,
  isCountryCode,
  validateCountryCode,
  COUNTRY_NAMES,
  COUNTRY_LIST,
  type ScholarViewDto,
  ScholarViewDtoSchema,
  type ScholarDetailDto,
  ScholarDetailDtoSchema,
  type ScholarStatsDto,
  ScholarStatsDtoSchema,
  type ScholarListItemDto,
  ScholarListItemDtoSchema,
  type ScholarContentItemDto,
  ScholarContentItemDtoSchema,
  type ScholarContentUnifiedDto,
  ScholarContentUnifiedDtoSchema,
  type ScholarTopicsDto,
  ScholarTopicsDtoSchema,
  type AdminScholarListItemDto,
  AdminScholarListItemDtoSchema,
  type AdminScholarListDto,
  AdminScholarListDtoSchema,
  type ScholarListDto,
  ScholarListDtoSchema,
  type CollectionSummaryDto,
  CollectionSummaryDtoSchema,
  type SeriesSummaryDto,
  SeriesSummaryDtoSchema,
  type SingleSummaryDto,
  SingleSummaryDtoSchema,
  type ListingFormat,
  ListingFormatSchema,
  type ScholarTitle,
  ScholarTitleSchema,
  type PresignedUrlPurpose,
  PresignedUrlPurposeSchema,
  type PresignedUrlRequestDto,
  PresignedUrlRequestDtoSchema,
  type PresignedUrlResponseDto,
  PresignedUrlResponseDtoSchema,
  type SearchCatalogParams,
  SearchCatalogParamsSchema,
  type SearchCatalogItemDto,
  SearchCatalogItemDtoSchema,
  type SearchCatalogResultsDto,
  SearchCatalogResultsDtoSchema,
  type FeedContentItemDto,
  FeedContentItemDtoSchema,
  type FeedScholarRowDto,
  FeedScholarRowDtoSchema,
  type FeedTopicRowDto,
  FeedTopicRowDtoSchema,
  type FeedItemDto,
  FeedItemDtoSchema,
  type FeedPageDto,
  FeedPageDtoSchema,
  type LibraryItemDto,
  LibraryItemDtoSchema,
  type LibraryPageDto,
  LibraryPageDtoSchema,
  type SavedSyncDto,
  SavedSyncDtoSchema,
  type UserProfileDto,
  UserProfileDtoSchema,
  type StreamResponseDto,
  StreamResponseDtoSchema,
  type AudioProgressDto,
  AudioProgressDtoSchema,
  type ProgressSyncItemDto,
  ProgressSyncItemDtoSchema,
  type ProgressSyncDto,
  ProgressSyncDtoSchema,
  type AdminPermission,
  AdminPermissionSchema,
  type AdminPermissionDto,
  AdminPermissionDtoSchema,
  type AdminPermissionsListDto,
  AdminPermissionsListDtoSchema,
  type GrantPermissionDto,
  GrantPermissionDtoSchema,
  type AdminUserListItemDto,
  AdminUserListItemDtoSchema,
  type AdminUserListDto,
  AdminUserListDtoSchema,
  ADMIN_PERMISSIONS,
  // New permission types
  type Permission,
  PermissionEnum,
  Permissions,
  PERMISSIONS_ARRAY,
  PERMISSION_LABELS,
  PERMISSION_DESCRIPTIONS,
  type UserRole,
  UserRoleEnum,
  type ScholarPermissionType,
  ScholarPermissionTypeEnum,
  PERMISSION_GROUPS,
  ROLE_DEFAULT_PERMISSIONS,
  type UserPermissionDto,
  UserPermissionDtoSchema,
  type UserRoleAssignmentDto,
  UserRoleAssignmentDtoSchema,
  type UserScholarRoleDto,
  UserScholarRoleDtoSchema,
  type UserTranslatorRoleDto,
  UserTranslatorRoleDtoSchema,
  type GrantPermissionRequest,
  GrantPermissionRequestSchema,
  type GrantRoleRequest,
  GrantRoleRequestSchema,
  type AssignScholarRequest,
  AssignScholarRequestSchema,
  type AssignTranslatorLanguageRequest,
  AssignTranslatorLanguageRequestSchema,
  type ScholarChipDto,
  ScholarChipDtoSchema,
  type ContentSuggestionDto,
  ContentSuggestionDtoSchema,
  type RecentProgressDto,
  RecentProgressDtoSchema,
  type QuickBrowseDto,
  QuickBrowseDtoSchema,
  type TranslationStatus,
  TranslationStatusSchema,
  type TranslationViewDto,
  TranslationViewDtoSchema,
  type SaveTranslationDto,
  SaveTranslationDtoSchema,
  type TranslationTarget,
  TranslationTargetSchema,
  type Locale,
  LocaleSchema,
  SUPPORTED_LOCALES,
  DEFAULT_LOCALE,
  RTL_LOCALES,
  type ContentOriginalFields,
  ContentOriginalFieldsSchema,
  type ScholarOriginalFields,
  ScholarOriginalFieldsSchema,
  type ListingProgressDto,
  ListingProgressDtoSchema,
  type ProgressUpdateDto,
  ProgressUpdateDtoSchema,
  type CreateListingDto,
  CreateListingDtoSchema,
  type SaveListingTranslationDto,
  SaveListingTranslationDtoSchema,
  type UpdateListingTranslationDto,
  UpdateListingTranslationDtoSchema,
  type ListingFormDataDto,
  ListingFormDataDtoSchema,
  type SaveTopicTranslationDto,
  SaveTopicTranslationDtoSchema,
  type UpdateTopicTranslationDto,
  UpdateTopicTranslationDtoSchema,
  type AdminTopicDetailDto,
  AdminTopicDetailDtoSchema,
  type CreateTopicWithTranslationsDto,
  CreateTopicWithTranslationsDtoSchema,
  type UpdateTopicWithTranslationsDto,
  UpdateTopicWithTranslationsDtoSchema,
  type CreateScholarDto,
  CreateScholarDtoSchema,
  type UpdateScholarDto,
  UpdateScholarDtoSchema,
  type SaveScholarTranslationDto,
  SaveScholarTranslationDtoSchema,
  type UpdateScholarTranslationDto,
  UpdateScholarTranslationDtoSchema,
  type ScholarFormDataDto,
  ScholarFormDataDtoSchema,
  type UpdateProfileDto,
  UpdateProfileDtoSchema,
  type UpdateLocaleDto,
  UpdateLocaleDtoSchema,
  type SearchQueryDto,
  SearchQueryDtoSchema,
} from "./types";

// Export route constants
export { routes, routeDefinitions, resolveRouteAccess } from "./routes";
export type { RouteAccess, RouteDefinition } from "./routes";

// Export shared navigation metadata
export {
  SECTION_TABS,
  DEFAULT_TABS,
  SECTION_LABELS,
  SECTION_ROUTES,
  type Section,
  type TabConfig,
} from "./navigation";

// Export query utilities (client, keys, hooks)
export {
  createQueryClient,
  queryKeys,
  shouldPersistQuery,
  getMaxAge,
  DEFAULT_MAX_AGE,
} from "./query";
export { useApiQuery, initApiClient } from "./query/hooks";
