// Export HTTP client
export { httpClient, getApiBaseUrl } from "./http";
export type { HttpClientConfig } from "./http";

// Export endpoint constants
export { endpoints } from "./endpoints";

// Export all shared types
export {
  type StatusValue,
  StatusValueSchema,
  type PaginationParams,
  PaginationParamsSchema,
  type ErrorResponseDto,
  ErrorResponseDtoSchema,
  type TopicSlug,
  TopicSlugSchema,
  type TopicViewDto,
  TopicViewDtoSchema,
  type TopicDetailDto,
  TopicDetailDtoSchema,
  type TopicLectureViewDto,
  TopicLectureViewDtoSchema,
  type AudioAssetViewDto,
  AudioAssetViewDtoSchema,
  type LectureViewDto,
  LectureViewDtoSchema,
  type ScholarRefDto,
  ScholarRefDtoSchema,
  type TopicRefDto,
  TopicRefDtoSchema,
  type AudioAssetDto,
  AudioAssetDtoSchema,
  type LectureRefDto,
  LectureRefDtoSchema,
  type SeriesContextDto,
  SeriesContextDtoSchema,
  type LectureDetailDto,
  LectureDetailDtoSchema,
  type RelatedLectureDto,
  RelatedLectureDtoSchema,
  type AdminLectureUpdateDto,
  AdminLectureUpdateDtoSchema,
  type AdminLectureActionDto,
  AdminLectureActionDtoSchema,
  type AdminLectureListItemDto,
  AdminLectureListItemDtoSchema,
  type AdminLectureListDto,
  AdminLectureListDtoSchema,
  type AdminLectureDetailDto,
  AdminLectureDetailDtoSchema,
  type BulkActionDto,
  BulkActionDtoSchema,
  type BulkActionResultDto,
  BulkActionResultDtoSchema,
  type ScholarViewDto,
  ScholarViewDtoSchema,
  type ScholarDetailDto,
  ScholarDetailDtoSchema,
  type ScholarStatsDto,
  ScholarStatsDtoSchema,
  type ScholarListItemDto,
  ScholarListItemDtoSchema,
  type ScholarContentItemDto,
  ScholarContentItemDtoSchema,
  type ScholarContentUnifiedDto,
  ScholarContentUnifiedDtoSchema,
  type ScholarTopicsDto,
  ScholarTopicsDtoSchema,
  type CollectionSummaryDto,
  CollectionSummaryDtoSchema,
  type SeriesSummaryDto,
  SeriesSummaryDtoSchema,
  type SingleSummaryDto,
  SingleSummaryDtoSchema,
  type ListingFormat,
  ListingFormatSchema,
  type ListingViewDto,
  ListingViewDtoSchema,
  type CollectionViewDto,
  CollectionViewDtoSchema,
  type AdminCollectionListItemDto,
  AdminCollectionListItemDtoSchema,
  type AdminCollectionDetailDto,
  AdminCollectionDetailDtoSchema,
  type SeriesViewDto,
  SeriesViewDtoSchema,
  type AdminSeriesListItemDto,
  AdminSeriesListItemDtoSchema,
  type AdminSeriesDetailDto,
  AdminSeriesDetailDtoSchema,
  type PresignedUrlPurpose,
  PresignedUrlPurposeSchema,
  type PresignedUrlRequestDto,
  PresignedUrlRequestDtoSchema,
  type PresignedUrlResponseDto,
  PresignedUrlResponseDtoSchema,
  type PlatformStatsDto,
  PlatformStatsDtoSchema,
  type SearchCatalogParams,
  SearchCatalogParamsSchema,
  type SearchCatalogItemDto,
  SearchCatalogItemDtoSchema,
  type SearchCatalogResultsDto,
  SearchCatalogResultsDtoSchema,
  type FeedContentItemDto,
  FeedContentItemDtoSchema,
  type FeedScholarRowDto,
  FeedScholarRowDtoSchema,
  type FeedTopicRowDto,
  FeedTopicRowDtoSchema,
  type FeedItemDto,
  FeedItemDtoSchema,
  type FeedPageDto,
  FeedPageDtoSchema,
  type LibraryItemDto,
  LibraryItemDtoSchema,
  type LibraryPageDto,
  LibraryPageDtoSchema,
  type SavedSyncDto,
  SavedSyncDtoSchema,
  type UserProfileDto,
  UserProfileDtoSchema,
  type LiveSessionStatus,
  LiveSessionStatusSchema,
  type LiveSessionPublicDto,
  LiveSessionPublicDtoSchema,
  type LiveSessionDeltaDto,
  LiveSessionDeltaDtoSchema,
  type LiveSessionDto,
  LiveSessionDtoSchema,
  type LiveSessionPageDto,
  LiveSessionPageDtoSchema,
  type LivestreamChannelDto,
  LivestreamChannelDtoSchema,
  type CreateLivestreamChannelDto,
  CreateLivestreamChannelDtoSchema,
  type UpdateLivestreamChannelDto,
  UpdateLivestreamChannelDtoSchema,
  type StreamResponseDto,
  StreamResponseDtoSchema,
  type AudioProgressDto,
  AudioProgressDtoSchema,
  type ProgressSyncItemDto,
  ProgressSyncItemDtoSchema,
  type ProgressSyncDto,
  ProgressSyncDtoSchema,
  type AdminPermission,
  AdminPermissionSchema,
  type AdminPermissionDto,
  AdminPermissionDtoSchema,
  type AdminPermissionsListDto,
  AdminPermissionsListDtoSchema,
  type GrantPermissionDto,
  GrantPermissionDtoSchema,
  type AdminUserListItemDto,
  AdminUserListItemDtoSchema,
  type AdminUserListDto,
  AdminUserListDtoSchema,
  ADMIN_PERMISSIONS,
  type ScholarChipDto,
  ScholarChipDtoSchema,
  type ContentSuggestionDto,
  ContentSuggestionDtoSchema,
  type RecentProgressDto,
  RecentProgressDtoSchema,
  type QuickBrowseDto,
  QuickBrowseDtoSchema,
  type TranslationStatus,
  TranslationStatusSchema,
  type TranslationViewDto,
  TranslationViewDtoSchema,
  type SaveTranslationDto,
  SaveTranslationDtoSchema,
  type TranslationTarget,
  TranslationTargetSchema,
  type Locale,
  LocaleSchema,
  SUPPORTED_LOCALES,
  DEFAULT_LOCALE,
  RTL_LOCALES,
  type ContentOriginalFields,
  ContentOriginalFieldsSchema,
  type ScholarOriginalFields,
  ScholarOriginalFieldsSchema,
  type LectureProgressDto,
  LectureProgressDtoSchema,
  type ProgressUpdateDto,
  ProgressUpdateDtoSchema,
  type CreateLectureDto,
  CreateLectureDtoSchema,
  type SaveLectureTranslationDto,
  SaveLectureTranslationDtoSchema,
  type UpdateLectureTranslationDto,
  UpdateLectureTranslationDtoSchema,
  type UpsertTopicDto,
  UpsertTopicDtoSchema,
  type SaveTopicTranslationDto,
  SaveTopicTranslationDtoSchema,
  type UpdateTopicTranslationDto,
  UpdateTopicTranslationDtoSchema,
  type CreateScholarDto,
  CreateScholarDtoSchema,
  type UpdateScholarDto,
  UpdateScholarDtoSchema,
  type SaveScholarTranslationDto,
  SaveScholarTranslationDtoSchema,
  type UpdateScholarTranslationDto,
  UpdateScholarTranslationDtoSchema,
  type CreateCollectionDto,
  CreateCollectionDtoSchema,
  type UpdateCollectionDto,
  UpdateCollectionDtoSchema,
  type SaveCollectionTranslationDto,
  SaveCollectionTranslationDtoSchema,
  type UpdateCollectionTranslationDto,
  UpdateCollectionTranslationDtoSchema,
  type SaveSeriesTranslationDto,
  SaveSeriesTranslationDtoSchema,
  type UpdateSeriesTranslationDto,
  UpdateSeriesTranslationDtoSchema,
  type CreateSeriesDto,
  CreateSeriesDtoSchema,
  type UpdateSeriesDto,
  UpdateSeriesDtoSchema,
  type CreateLiveSessionDto,
  CreateLiveSessionDtoSchema,
  type UpdateLiveSessionDto,
  UpdateLiveSessionDtoSchema,
  type UpdateLiveSessionStatusDto,
  UpdateLiveSessionStatusDtoSchema,
  type UpdateProfileDto,
  UpdateProfileDtoSchema,
  type UpdateLocaleDto,
  UpdateLocaleDtoSchema,
  type SearchQueryDto,
  SearchQueryDtoSchema,
} from "./types";

// Export route constants
export { routes, routeDefinitions, resolveRouteAccess } from "./routes";
export type { RouteAccess, RouteDefinition } from "./routes";

// Export shared navigation metadata
export {
  SECTION_TABS,
  DEFAULT_TABS,
  SECTION_LABELS,
  SECTION_ROUTES,
  type Section,
  type TabConfig,
} from "./navigation";

// Export query utilities (client, keys, hooks)
export { createQueryClient, queryKeys } from "./query";
export { useApiQuery, initApiClient } from "./query/hooks";
