import { COMPANY_NAME, COMPANY_URL, COMPANY_COUNTRY } from "./company";

export const PRIVACY_DEFINITIONS = [
  {
    term: "Account",
    definition:
      "means a unique account created for You to access our Service or parts of our Service.",
  },
  {
    term: "Application",
    definition: `refers to ${COMPANY_NAME}, the software program provided by the Company.`,
  },
  {
    term: "Company",
    definition: `(referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to ${COMPANY_NAME}.`,
  },
  {
    term: "Cookies",
    definition:
      "are small files or similar technologies (such as browser local storage) that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
  },
  {
    term: "Country",
    definition: `refers to: ${COMPANY_COUNTRY}`,
  },
  {
    term: "Device",
    definition:
      "means any device that can access the Service such as a computer, a cell phone or a digital tablet.",
  },
  {
    term: "Personal Data",
    definition:
      '(referred to as "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.',
  },
  {
    term: "Service",
    definition: "refers to the Application or the Website or both.",
  },
  {
    term: "Service Provider",
    definition:
      "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
  },
  {
    term: "Usage Data",
    definition:
      "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
  },
  {
    term: "Website",
    definition: `refers to ${COMPANY_NAME}, accessible from ${COMPANY_URL}.`,
  },
  {
    term: "You",
    definition:
      "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
  },
];

export const DATA_USE_PURPOSES = [
  {
    title: "To provide and maintain our Service",
    desc: "including to monitor the usage of our Service.",
  },
  {
    title: "To manage Your Account",
    desc: "to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
  },
  {
    title: "For support and communication",
    desc: "We collect Your email address to enable You to contact Us for support if You experience issues with our Service. We do not use Your email to contact You proactively. Any communications from Us to You will be delivered through in-app notifications only.",
  },
  {
    title: "To manage Your requests",
    desc: "To attend and manage Your requests to Us.",
  },
  {
    title: "For business transfers",
    desc: "We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.",
  },
  {
    title: "For other purposes",
    desc: "We may use Your information for other purposes, such as data analysis, identifying usage trends, and to evaluate and improve our Service and your experience.",
  },
];

export const DATA_SHARING = [
  {
    title: "With Service Providers",
    desc: "We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service.",
  },
  {
    title: "For business transfers",
    desc: "We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.",
  },
  {
    title: "With Your consent",
    desc: "We may disclose Your Personal Data for any other purpose with Your consent.",
  },
];
