// Auto-generated by export-real-data.ts
import type { SingleSeed } from "../types.js";

export const SINGLES: SingleSeed[] = [
  {
    id: 100,
    scholarIdx: 1,
    slug: "fawzan-nawaqidul-islam",
    title: "نواقض الإسلام",
    titleEn: "Nullifiers of Islam",
    desc: "",
    topicIdx: 0,
    durationMin: 90,
    audioUrl:
      "https://preview-cdn.salafidurus.com/audio/fawzan-nawaqidul-islam/fawzan-nawaqidul-islam.mp3",
    objectKey: "audio/fawzan-nawaqidul-islam/fawzan-nawaqidul-islam.mp3",
    audioFormat: "mp3",
    sizeBytes: 46293191,
    audioSource: "r2",
    language: "ar",
  },
];
