// Auto-generated by export-real-data.ts
import { uuid } from "../helpers.js";

export interface TopicData {
  id: string;
  slug: string;
  name: string;
  nameEn: string;
  orderIndex?: number;
}

export const TOPICS: TopicData[] = [
  { id: uuid(10), slug: "aqeedah", name: "العقيدة", nameEn: "Aqeedah", orderIndex: 0 },
  { id: uuid(11), slug: "tafsir", name: "التفسير", nameEn: "Tafsir", orderIndex: 1 },
  { id: uuid(12), slug: "hadith", name: "الحديث", nameEn: "Hadith", orderIndex: 2 },
  { id: uuid(13), slug: "fiqh", name: "الفقه", nameEn: "Fiqh", orderIndex: 3 },
  { id: uuid(14), slug: "nahw", name: "النحو", nameEn: "Nahw", orderIndex: 4 },
  { id: uuid(15), slug: "seerah", name: "السيرة", nameEn: "Seerah", orderIndex: 6 },
];
