apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.bottomaccessory'
version = '0.1.0'

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
  namespace 'expo.modules.bottomaccessory'
  compileSdkVersion safeExtGet("compileSdkVersion", 35)

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    targetSdkVersion safeExtGet("targetSdkVersion", 35)
  }

  lintOptions {
    abortOnError false
  }

  publishing {
    singleVariant("release")
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${safeExtGet('kotlinVersion', '2.0.21')}"
  implementation "com.google.android.material:material:1.12.0"
}
