export { Footer } from "./components/footer/footer";
export { Sidebar } from "./components/sidebar/sidebar";
export { TopAuthStrip } from "./components/top-auth-strip/top-auth-strip";
export { AdaptiveShell } from "./components/AdaptiveShell/AdaptiveShell";
export { SECTION_TABS, SECTION_ROUTES, SECTION_LABELS } from "./types.native";
export type { ActiveNavigationState, Section, ShellMode, TabConfig } from "./types.native";
export { getCurrentSection, getActiveTabFromPath } from "./utils/get-current-section";
export { buildSearchHomeHref, buildSectionHref } from "./utils/shell-navigation.native";
export { useActiveNavigationState } from "./hooks/use-active-navigation-state";
export { useNavigationStore } from "./store/navigation-store";
