import type { Permission } from "@sd/core-contracts";

export const PERMISSION_LABELS: Record<Permission, string> = {
  SCHOLARS_EDIT: "Manage Scholars",
  TOPICS_EDIT: "Manage Topics",
  LISTINGS_EDIT: "Manage Content",
  USERS_VIEW: "View Users",
  USERS_GRANT_PERMISSIONS: "Manage Permissions",
  USERS_GRANT_ROLES: "Manage Roles",
  SCHOLARS_VIEW: "View Scholars",
  SCHOLARS_CREATE: "Create Scholars",
  SCHOLARS_DELETE: "Delete Scholars",
  SCHOLARS_PUBLISH: "Publish Scholars",
  LISTINGS_VIEW: "View Content",
  LISTINGS_CREATE: "Create Content",
  LISTINGS_DELETE: "Delete Content",
  LISTINGS_PUBLISH: "Publish Content",
  TOPICS_VIEW: "View Topics",
  TOPICS_CREATE: "Create Topics",
  TOPICS_DELETE: "Delete Topics",
  TOPICS_PUBLISH: "Publish Topics",
  TRANSLATIONS_VIEW: "View Translations",
  TRANSLATIONS_CREATE: "Create Translations",
  TRANSLATIONS_EDIT: "Edit Translations",
  TRANSLATIONS_DELETE: "Delete Translations",
  TRANSLATIONS_PUBLISH: "Publish Translations",
  MEDIA_UPLOAD: "Upload Media",
  MEDIA_DELETE: "Delete Media",
  USERS_EDIT: "Edit Users",
  USERS_DELETE: "Delete Users",
};

export const PERMISSION_DESCRIPTIONS: Record<Permission, string> = {
  SCHOLARS_EDIT: "Add, edit, and remove scholar profiles",
  TOPICS_EDIT: "Create and organize topic categories",
  LISTINGS_EDIT: "Publish, archive, and manage lectures and series",
  USERS_VIEW: "View user accounts and their details",
  USERS_GRANT_PERMISSIONS: "Grant and revoke user permissions",
  USERS_GRANT_ROLES: "Assign roles to users",
  SCHOLARS_VIEW: "View scholar profiles",
  SCHOLARS_CREATE: "Create new scholar profiles",
  SCHOLARS_DELETE: "Delete scholar profiles",
  SCHOLARS_PUBLISH: "Publish scholar profiles",
  LISTINGS_VIEW: "View content listings",
  LISTINGS_CREATE: "Create new content listings",
  LISTINGS_DELETE: "Delete content listings",
  LISTINGS_PUBLISH: "Publish content",
  TOPICS_VIEW: "View topics",
  TOPICS_CREATE: "Create new topics",
  TOPICS_DELETE: "Delete topics",
  TOPICS_PUBLISH: "Publish topics",
  TRANSLATIONS_VIEW: "View translations",
  TRANSLATIONS_CREATE: "Create translations",
  TRANSLATIONS_EDIT: "Edit translations",
  TRANSLATIONS_DELETE: "Delete translations",
  TRANSLATIONS_PUBLISH: "Publish translations",
  MEDIA_UPLOAD: "Upload media files",
  MEDIA_DELETE: "Delete media files",
  USERS_EDIT: "Edit user accounts",
  USERS_DELETE: "Delete user accounts",
};
